env: "local" # or dev, prod
hash_salt: ""

token:
  access:
    secret: ""
    ttl: 15m
  refresh:
    ttl: 720h

http:
  address: "0.0.0.0:7531"
  timeout: 4s
  idle_timeout: 60s

db:
  connection_uri: ""
