basePath: /
definitions:
  request.URL:
    properties:
      alias:
        type: string
      url:
        type: string
    type: object
  request.UserCreate:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  request.UserLogIn:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  response.Error:
    properties:
      message:
        type: string
    type: object
  response.TokenPair:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  response.URL:
    properties:
      alias:
        type: string
      redirects:
        type: integer
      url:
        type: string
    type: object
  response.URLCreated:
    properties:
      alias:
        type: string
      url:
        type: string
    type: object
  response.User:
    properties:
      email:
        type: string
      username:
        type: string
    type: object
host: localhost:8081/api
info:
  contact: {}
  description: API Server for URL Shortener Application
  title: URL Shortener App API
  version: "1.0"
paths:
  /session:
    delete:
      description: Close a session
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - AccessToken: []
      summary: User logout
      tags:
      - session
    post:
      consumes:
      - application/json
      description: Creates a session
      parameters:
      - description: Account credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/request.UserLogIn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.TokenPair'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      summary: User login
      tags:
      - session
  /url:
    post:
      consumes:
      - application/json
      description: Creates a URL in database, assigned to user
      parameters:
      - description: Url data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/request.URL'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.URLCreated'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Error'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - AccessToken: []
      summary: Create URL
      tags:
      - url
  /url/:alias:
    delete:
      description: Deletes an url from database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/response.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - AccessToken: []
      summary: Delete URL
      tags:
      - url
  /user:
    post:
      consumes:
      - application/json
      description: Creates a user in database
      parameters:
      - description: User data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/request.UserCreate'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      summary: User registration
      tags:
      - user
  /user/me:
    delete:
      description: Delete me from database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - AccessToken: []
      summary: Delete me
      tags:
      - user
  /user/me/urls:
    get:
      description: Get all URLs created by user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.URL'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - AccessToken: []
      summary: Get URLs
      tags:
      - user
securityDefinitions:
  AccessToken:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
