name: Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Docker login
        uses: actions/checkout@v2
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD;
      - name: Docker build
        run: docker build -t ${{ secrets.DOCKER_USER }}/makeshort-backend .
      - name: Push image
        run: docker push ${{ secrets.DOCKER_USER }}/makeshort-backend

      - name: Run command on remote server
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{secrets.SSH_HOST}}
          user: ${{secrets.SSH_USER}}
          private_key: ${{secrets.SSH_PRIVATE_KEY}}
          command: |
            cd ${{ secrets.PROJECT_DIR }};
            git checkout master;
            git pull;
            docker compose down;
#            docker build -t makeshort-backend .;
            docker compose up -t;

#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v2
#      - name: Set up Go
#        uses: actions/setup-go@v2
#        with:
#          go-version: 1.21
#      - name: Build app
#        run: |
#          go mod download
#          make build