name: Build App

on:
  push:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.HOST }}
      DEPLOY_DIRECTORY: /root/apps/makeshort/backend
      CONFIG_PATH: /root/apps/makeshort/backend/config/prod.yaml
      ENV_FILE_PATH: /root/apps/makeshort/backend/config.env

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.4
      - name: Build app
        run: |
          go mod download
          make build